add beta_chelsea
emorihouse/emorihouse.github.io pull request #57
Opened 2023-01-28 13:17 UTC by betachelsea

2023入居希望です！

2023-02-11 00:17 UTC, emorihouse requested changes
@betachelsea 

Conflictしてしまったので、修正お願いしたいです〜！

2023-03-05 01:47 UTC, betachelsea commented
@emorihouse 確認遅くなりすみません…！ :bow: 修正しました！

2023-03-05 01:52 UTC, emorima approved these changes

2023-03-05 01:59 UTC, emorihouse approved these changes

2023-03-05 01:59 UTC, merged